# Generated by Django 5.2.17 on 2026-08-23 23:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='URL')),
                ('bajada', models.CharField(blank=True, max_length=255, verbose_name='Bajada')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo')),
                ('imagen', models.ImageField(blank=True, upload_to='noticias/', verbose_name='Imagen de portada')),
                ('destacada', models.BooleanField(default=False, verbose_name='Destacada en el carrusel')),
                ('publicada', models.BooleanField(default=True, verbose_name='Publicada')),
                ('publicada_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-publicada_en'],
            },
        ),
        migrations.CreateModel(
            name='SlideCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('texto', models.CharField(blank=True, max_length=255, verbose_name='Texto')),
                ('imagen', models.ImageField(blank=True, upload_to='carrusel/', verbose_name='Imagen')),
                ('enlace', models.CharField(blank=True, max_length=255, verbose_name='Enlace interno o URL')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('desde', models.DateField(blank=True, null=True, verbose_name='Visible desde')),
                ('hasta', models.DateField(blank=True, null=True, verbose_name='Visible hasta')),
            ],
            options={
                'verbose_name': 'Slide del carrusel',
                'verbose_name_plural': 'Slides del carrusel',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='URL')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Término')),
                ('lugar', models.CharField(blank=True, max_length=180, verbose_name='Lugar')),
                ('imagen', models.ImageField(blank=True, upload_to='eventos/', verbose_name='Imagen')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='juntas.junta', verbose_name='Junta')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
