# Generated by Django 5.2.17 on 2026-08-23 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenido', '0001_initial'),
        ('juntas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='junta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='juntas.junta', verbose_name='Junta'),
        ),
        migrations.AddField(
            model_name='slidecarrusel',
            name='junta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='juntas.junta', verbose_name='Junta'),
        ),
        migrations.AlterUniqueTogether(
            name='evento',
            unique_together={('junta', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='noticia',
            unique_together={('junta', 'slug')},
        ),
    ]
