# Generated by Django 5.2.17 on 2026-10-01 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(help_text='Cuenta la actividad con detalle. Las fotos van en la galería de abajo.', verbose_name='Crónica del evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, help_text='La foto principal del evento. Sube más abajo las del día.', upload_to='eventos/', verbose_name='Foto de portada'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(help_text='Cuenta lo que pasó, como en un blog. Separa los párrafos con una línea en blanco.', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, help_text='La foto principal del artículo. Sin foto la noticia casi no se ve en el inicio.', upload_to='noticias/', verbose_name='Foto de portada'),
        ),
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='eventos/galeria/', verbose_name='Foto')),
                ('pie', models.CharField(blank=True, max_length=180, verbose_name='Pie de foto')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='contenido.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Foto del evento',
                'verbose_name_plural': 'Galería de fotos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FotoNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias/galeria/', verbose_name='Foto')),
                ('pie', models.CharField(blank=True, max_length=180, verbose_name='Pie de foto')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='contenido.noticia', verbose_name='Noticia')),
            ],
            options={
                'verbose_name': 'Foto de la noticia',
                'verbose_name_plural': 'Galería de fotos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
