# Generated by Django 5.2.17 on 2026-08-23 23:31

import django.db.models.deletion
import django.utils.timezone
import vecinos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, validators=[vecinos.models._validar_rut_campo], verbose_name='RUT')),
                ('nombres', models.CharField(max_length=120, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=80, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=80, verbose_name='Apellido materno')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Vigente')),
                ('mostrar_cumpleanos', models.BooleanField(default=False, help_text='Solo se publica el nombre de pila y la inicial del apellido.', verbose_name='Mostrar cumpleaños en el home')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de ingreso')),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vecinos', to='juntas.junta', verbose_name='Junta')),
            ],
            options={
                'verbose_name': 'Vecino',
                'verbose_name_plural': 'Vecinos',
                'ordering': ['apellido_paterno', 'nombres'],
                'unique_together': {('junta', 'rut')},
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código de verificación')),
                ('contenido_hash', models.CharField(max_length=64, verbose_name='Huella del contenido')),
                ('emitido_en', models.DateTimeField(auto_now_add=True, verbose_name='Emitido')),
                ('anulado', models.BooleanField(default=False, verbose_name='Anulado')),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de solicitud')),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='juntas.junta', verbose_name='Junta')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='vecinos.vecino', verbose_name='Vecino')),
            ],
            options={
                'verbose_name': 'Certificado de residencia',
                'verbose_name_plural': 'Certificados de residencia',
                'ordering': ['-emitido_en'],
            },
        ),
    ]
