# Generated by Django 5.2.17 on 2026-08-24 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vecinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vecino',
            options={'ordering': ['apellido_paterno', 'nombres'], 'verbose_name': 'Socio titular', 'verbose_name_plural': 'Socios titulares'},
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('rut', models.CharField(blank=True, max_length=12, verbose_name='RUT')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_familiar', to='vecinos.vecino', verbose_name='Socio titular')),
            ],
            options={
                'verbose_name': 'Integrante del grupo familiar',
                'verbose_name_plural': 'Grupo familiar',
                'ordering': ['id'],
            },
        ),
    ]
