# Generated by Django 5.2.17 on 2026-08-24 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntas', '0002_alter_junta_presidente_cargodirectiva'),
        ('vecinos', '0002_alter_vecino_options_familiar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-emitido_en'], 'verbose_name': 'Certificado emitido', 'verbose_name_plural': 'Certificados emitidos (registro)'},
        ),
        migrations.AddField(
            model_name='certificado',
            name='direccion_impresa',
            field=models.CharField(default='', max_length=255, verbose_name='Domicilio en el certificado'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='emitido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='vecinos.familiar', verbose_name='Integrante del grupo familiar'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='nombre_impreso',
            field=models.CharField(default='', max_length=180, verbose_name='Nombre en el certificado'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observación interna'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='origen',
            field=models.CharField(choices=[('web_rut', 'Solicitud web (socio titular)'), ('manual', 'Emisión de la directiva')], default='web_rut', max_length=20, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='rut_impreso',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT en el certificado'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='junta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='juntas.junta', verbose_name='Junta'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='vecino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='vecinos.vecino', verbose_name='Socio titular (si aplica)'),
        ),
        migrations.CreateModel(
            name='DisenoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Si lo dejas vacío se usa el logo de la junta.', upload_to='certificados/diseno/', verbose_name='Logo del certificado')),
                ('mostrar_logo', models.BooleanField(default=True, verbose_name='Mostrar logo')),
                ('titulo', models.CharField(default='CERTIFICADO DE RESIDENCIA', max_length=120, verbose_name='Título')),
                ('cuerpo', models.TextField(default='La <<junta.nombre>> certifica que <<nombre.socio>>, RUT <<rut.socio>>, reside en <<domicilio>><<comuna.frase>>, y se encuentra registrado(a) como integrante vigente de esta organización. Documento emitido el <<fecha.emision>> bajo la presidencia de <<presidente>>.', help_text='Variables: <<nombre.socio>> o <<nombre>>, <<rut.socio>> o <<rut>>, <<domicilio>>, <<junta.nombre>>, <<junta.comuna>>, <<junta.direccion>>, <<presidente>>, <<fecha.emision>>, <<codigo>>, <<socio.titular>>, <<comuna.frase>>.', verbose_name='Texto del certificado')),
                ('mostrar_caja_datos', models.BooleanField(default=True, verbose_name='Mostrar caja de datos')),
                ('mostrar_nombre', models.BooleanField(default=True, verbose_name='Caja: nombre')),
                ('mostrar_rut', models.BooleanField(default=True, verbose_name='Caja: RUT')),
                ('mostrar_domicilio', models.BooleanField(default=True, verbose_name='Caja: domicilio')),
                ('mostrar_fecha', models.BooleanField(default=True, verbose_name='Caja: fecha de emisión')),
                ('mostrar_codigo', models.BooleanField(default=True, verbose_name='Caja: código de verificación')),
                ('mostrar_qr', models.BooleanField(default=True, verbose_name='Mostrar código QR')),
                ('texto_verificacion', models.TextField(default='Verifique este documento en el sitio de la junta con el código <<codigo>> o escaneando el QR. Si el PDF fue alterado, el verificador mostrará los datos oficiales.', help_text='Puedes usar <<codigo>>. El QR se dibuja al lado de la caja de datos.', verbose_name='Texto junto al verificador')),
                ('texto_pie', models.CharField(blank=True, default='Huella: <<huella>> · <<url.verificacion>>', help_text='Variables extra: <<huella>>, <<url.verificacion>>, <<codigo>>.', max_length=255, verbose_name='Pie de página')),
                ('junta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diseno_certificado', to='juntas.junta', verbose_name='Junta')),
            ],
            options={
                'verbose_name': 'Diseño de certificado',
                'verbose_name_plural': 'Diseño de certificados',
            },
        ),
    ]
