# Generated by Django 5.2.17 on 2026-08-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vecinos', '0004_rellenar_datos_impresos'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenocertificado',
            name='logo_alto',
            field=models.DecimalField(decimal_places=2, default='2.20', max_digits=5, verbose_name='Alto del logo (cm)'),
        ),
        migrations.AddField(
            model_name='disenocertificado',
            name='logo_ancho',
            field=models.DecimalField(decimal_places=2, default='2.20', max_digits=5, verbose_name='Ancho del logo (cm)'),
        ),
        migrations.AddField(
            model_name='disenocertificado',
            name='logo_x',
            field=models.DecimalField(decimal_places=2, default='1.60', max_digits=5, verbose_name='Logo X (cm desde la izquierda)'),
        ),
        migrations.AddField(
            model_name='disenocertificado',
            name='logo_y',
            field=models.DecimalField(decimal_places=2, default='0.95', max_digits=5, verbose_name='Logo Y (cm desde arriba)'),
        ),
    ]
