# Generated by Django 5.2.17 on 2026-08-24 01:07

import vecinos.layout
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vecinos', '0005_disenocertificado_logo_alto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disenocertificado',
            name='layout',
            field=models.JSONField(blank=True, default=vecinos.layout.layout_por_defecto, verbose_name='Posición de cada bloque'),
        ),
    ]
