# Generated by Django 5.2.17 on 2026-08-23 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntas', '0002_alter_junta_presidente_cargodirectiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('titulo', models.CharField(max_length=180, verbose_name='Actividad')),
                ('descripcion', models.TextField(verbose_name='Qué se hizo y con qué recursos')),
                ('imagen', models.ImageField(blank=True, upload_to='transparencia/actividades/', verbose_name='Foto')),
                ('documento', models.FileField(blank=True, upload_to='transparencia/actividades/', verbose_name='Acta o informe (PDF)')),
                ('publicada', models.BooleanField(default=True, verbose_name='Visible en el sitio')),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_actividad', to='juntas.junta', verbose_name='Junta')),
            ],
            options={
                'verbose_name': 'Rendición de actividad',
                'verbose_name_plural': 'Rendiciones de actividades',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RendicionGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('concepto', models.CharField(max_length=180, verbose_name='Concepto')),
                ('categoria', models.CharField(choices=[('cuotas', 'Cuotas y aportes'), ('sede', 'Sede y mantención'), ('actividades', 'Actividades y eventos'), ('servicios', 'Servicios e insumos'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto (CLP)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Detalle')),
                ('documento', models.FileField(blank=True, help_text='PDF o imagen. Queda descargable en la web pública.', upload_to='transparencia/gastos/', verbose_name='Boleta, factura o planilla')),
                ('publicada', models.BooleanField(default=True, verbose_name='Visible en el sitio')),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='juntas.junta', verbose_name='Junta')),
            ],
            options={
                'verbose_name': 'Rendición de gasto',
                'verbose_name_plural': 'Rendiciones de gastos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
