# Generated by Django 5.2.17 on 2026-10-01 02:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntas', '0004_tesoreria_cuotas_y_directiva'),
        ('vecinos', '0006_disenocertificado_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto')),
                ('detalle', models.CharField(max_length=255, verbose_name='Detalle')),
                ('categoria', models.CharField(blank=True, help_text='Ej: cuota, bingos, luz, aseo, materiales.', max_length=80, verbose_name='Categoría')),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='juntas.junta', verbose_name='Junta')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='vecinos.vecino', verbose_name='Socio (si aplica)')),
            ],
            options={
                'verbose_name': 'Ingreso o egreso',
                'verbose_name_plural': 'Ingresos y egresos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto')),
                ('pagado_en', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de pago')),
                ('observacion', models.CharField(blank=True, max_length=180, verbose_name='Nota')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_cuota', to='vecinos.vecino', verbose_name='Socio titular')),
            ],
            options={
                'verbose_name': 'Pago de cuota',
                'verbose_name_plural': 'Pagos de cuotas',
                'ordering': ['-anio', '-mes', 'vecino'],
                'unique_together': {('vecino', 'anio', 'mes')},
            },
        ),
    ]
