# Generated by Django 5.2.17 on 2026-10-01 04:10

import django.db.models.deletion
import tesoreria.layout
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntas', '0004_tesoreria_cuotas_y_directiva'),
        ('tesoreria', '0001_tesoreria_cuotas_y_directiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisenoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Si lo dejas vacío se usa el logo de la junta.', upload_to='comprobantes/diseno/', verbose_name='Logo del comprobante')),
                ('mostrar_logo', models.BooleanField(default=True, verbose_name='Mostrar logo')),
                ('titulo', models.CharField(default='Comprobante de pago', max_length=120, verbose_name='Título')),
                ('cuerpo', models.TextField(default='Fecha de pago: <<fecha.pago>>', verbose_name='Subtítulo')),
                ('texto_pie', models.TextField(default='Documento emitido por tesorería de <<junta.nombre>>.\nConserve este comprobante como constancia de pago.', verbose_name='Pie de página')),
                ('mostrar_caja_datos', models.BooleanField(default=True, verbose_name='Mostrar datos del socio')),
                ('mostrar_nombre', models.BooleanField(default=True, verbose_name='Caja: nombre')),
                ('mostrar_rut', models.BooleanField(default=True, verbose_name='Caja: RUT')),
                ('mostrar_domicilio', models.BooleanField(default=True, verbose_name='Caja: domicilio')),
                ('mostrar_fecha', models.BooleanField(default=True, verbose_name='Caja: fecha')),
                ('layout', models.JSONField(blank=True, default=tesoreria.layout.layout_por_defecto, verbose_name='Posición de cada bloque')),
                ('junta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diseno_comprobante', to='juntas.junta', verbose_name='Junta')),
            ],
            options={
                'verbose_name': 'Diseño de comprobante',
                'verbose_name_plural': 'Diseño de comprobantes',
            },
        ),
    ]
