# Generated by Django 5.2.17 on 2026-08-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Se usa en la web: /huente/', unique=True, verbose_name='URL')),
                ('logo', models.ImageField(blank=True, upload_to='juntas/logos/', verbose_name='Logo')),
                ('color_primario', models.CharField(default='#2D8A4E', max_length=7, verbose_name='Color primario')),
                ('color_acento', models.CharField(default='#F4C430', max_length=7, verbose_name='Color acento')),
                ('color_apoyo', models.CharField(default='#3A8FCD', max_length=7, verbose_name='Color de apoyo')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=80, verbose_name='Comuna')),
                ('presidente', models.CharField(blank=True, max_length=150, verbose_name='Presidente/a')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Quiénes somos')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Junta de vecinos',
                'verbose_name_plural': 'Juntas de vecinos',
                'ordering': ['nombre'],
            },
        ),
    ]
