# Generated by Django 5.2.17 on 2026-08-23 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junta',
            name='presidente',
            field=models.CharField(blank=True, help_text='Nombre que aparece en el certificado de residencia.', max_length=150, verbose_name='Presidente/a (certificados)'),
        ),
        migrations.CreateModel(
            name='CargoDirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Ej: Presidente/a, Secretario/a, Tesorero/a', max_length=80, verbose_name='Cargo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('foto', models.ImageField(blank=True, upload_to='juntas/directiva/', verbose_name='Foto')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='juntas.junta', verbose_name='Junta')),
            ],
            options={
                'verbose_name': 'Integrante de la directiva',
                'verbose_name_plural': 'Directiva',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
