# Generated by Django 5.2.17 on 2026-10-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntas', '0003_slug_huentelauquen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargodirectiva',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Presentación'),
        ),
        migrations.AddField(
            model_name='cargodirectiva',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='cargodirectiva',
            name='periodo',
            field=models.CharField(blank=True, help_text='Ej: 2024-2026', max_length=80, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='cargodirectiva',
            name='rut',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='cargodirectiva',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='junta',
            name='certificado_con_deuda',
            field=models.BooleanField(default=True, help_text='Si está apagado, el socio titular con meses impagos no puede pedir el certificado en la web.', verbose_name='Permitir certificado con cuotas impagas'),
        ),
        migrations.AddField(
            model_name='junta',
            name='valor_cuota',
            field=models.DecimalField(decimal_places=0, default=0, help_text='En pesos. Si es 0, no se cobran cuotas.', max_digits=10, verbose_name='Valor de la cuota mensual'),
        ),
        migrations.AlterField(
            model_name='junta',
            name='slug',
            field=models.SlugField(help_text='Se usa en la web: /huentelauquen/', unique=True, verbose_name='URL'),
        ),
    ]
